### ISSUE TITLE
Fix broken claims with brand logo image configured

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#91]

**Comment by ghost** [comment]
for what i see, it does not work because of a CORS problem. 

`Access to image at 'https://logobrand.com/wp-content/uploads/2019/03/11748_Logobrand_RAINBOW-logo.png' from origin 'https://dashboard.thx.network' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

We could fix that saving the base64 loo image in the db.
What do you think @peterpolman ?

**Comment by peterpolman** [comment]
What in your experience is exactly not working? 

I want to make sure we're talking about the same issue:) if I recall correctly, Steffen mentioned not being able to see the claim urls in the RewardCard in Dashboard. Are you saying this CORS issue is the cause of that?

**Comment by ghost** [comment]
yep ,i am not able to se the logo inside the qrcode and the claim url is empty

**Comment by peterpolman** [comment]
FYI: There is also a PR ready in API for uploading those brand images instead of storing an external URL. So that might already solve that CORS issue.

**Comment by peterpolman** [comment]
> yep ,i am not able to se the logo inside the qrcode and the claim url is empty

Ah great, let me do a quick review within the next hour on that PR then and merge it to dev so we can test there if it fixes it. I will ping you when it is deployed.

**Comment by ghost** [comment]
it can be easily fixed if we do this temporary fix:
```javascript
getBase64Image(logoImgUrl).then((data) => {
                    this.imgData = data;
                    //this.claimURL = `${WALLET_URL}/claim/${this.reward.claims[0]._id}`;
                });
                this.claimURL = `${WALLET_URL}/claim/${this.reward.claims[0]._id}`;`
```

**Comment by ghost** [comment]
created PR https://github.com/thxprotocol/dashboard/pull/96 
@peterpolman
